services:
  db_changelog:
      image: postgres
      volumes:
        - postgres_volume:/var/lib/postgresql/data
      env_file:
        - ../.env
      ports:
        - "5434:5432"


volumes:
  postgres_volume: